# Generated by Django 6.0.4 on 2026-04-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.CharField(max_length=255)),
                (
                    "transaction_type",
                    models.CharField(choices=[("DEPOSIT", "입금"), ("WITHDRAWAL", "출금")], max_length=20),
                ),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="account.account")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
