# Generated by Django 6.0.3 on 2026-04-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, choices=[('EMPLOYEE', '직장인'), ('STUDENT', '학생'), ('FREELANCER', '프리랜서'), ('HOUSEWIFE', '주부'), ('OTHER', '기타')], default='', max_length=20),
        ),
    ]
