# Generated by Django 6.0.3 on 2026-04-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="통장", max_length=20)),
                ("number", models.CharField(max_length=20, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CHECKING", "입출금"),
                            ("SAVINGS", "적금"),
                            ("DEPOSIT", "예금"),
                            ("OVERDRAFT", "마이너스"),
                            ("LOAN", "대출"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("004", "국민은행"),
                            ("088", "신한은행"),
                            ("020", "우리은행"),
                            ("081", "하나은행"),
                            ("011", "농협은행"),
                            ("003", "기업은행"),
                            ("023", "SC제일은행"),
                            ("027", "씨티은행"),
                            ("032", "부산은행"),
                            ("031", "대구은행"),
                            ("090", "카카오뱅크"),
                            ("092", "토스뱅크"),
                            ("089", "케이뱅크"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("balance", models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
            options={
                "verbose_name": "계좌",
                "verbose_name_plural": "계좌 목록",
                "ordering": ["name", "-updated_at"],
            },
        ),
    ]
