# Generated by Django 6.0.3 on 2026-04-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_type_account_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_alerts', to='account.account')),
            ],
            options={
                'verbose_name': '잔액 알림',
                'verbose_name_plural': '잔액 알림 목록',
                'ordering': ['-created_at'],
                'unique_together': {('account', 'threshold')},
            },
        ),
    ]
