# Generated by Django 6.0.3 on 2026-04-10 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about', models.CharField(max_length=50)),
                ('analysis_type', models.CharField(choices=[('WEEKLY', '주간'), ('MONTHLY', '월간')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='analysis/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '소비 분석',
                'verbose_name_plural': '소비 분석 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
